# Generated by Django 4.0 on 2022-02-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=20000)),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='blog/image')),
            ],
        ),
    ]
