# Generated by Django 4.0 on 2022-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=20000)),
                ('autor', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='blog/image')),
            ],
        ),
    ]
