# Generated by Django 4.0 on 2022-01-31 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='autor',
            new_name='author',
        ),
    ]
