# Generated by Django 4.0.2 on 2022-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_autor_content_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
    ]
