# Generated by Django 4.0.2 on 2022-03-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='phone',
        ),
    ]
